#!/usr/bin/python3

import argparse
import sys

from pathlib import Path

# if called from git source, add parent dir to python path
if Path(__file__).parent.name == 'scripts':
    sys.path.insert(0, str(Path(__file__).parent.parent))

from saucery import Grocer


def main(args=None):
    parser = argparse.ArgumentParser()
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument('-l', '--list', action='store_true',
                         help='Only list files')
    actions.add_argument('-C', '--clean', action='store_true',
                         help='Clean (remove) any empty shelves')
    actions.add_argument('-s', '--stock', action='store_true',
                         help='Stock the new sosreports/files')
    actions.add_argument('-e', '--expired', action='store_true',
                         help='Put old unknown sosreports/files in the trash')
    (grocer, opts) = Grocer.parse(parser=parser, actions=actions, args=args)

    if opts.clean:
        grocer.clean()
    elif opts.stock:
        grocer.stock()
    elif opts.expired:
        grocer.dispose()
    elif opts.list:
        deliveries = grocer.grocery.deliveries
        if deliveries:
            grocer.LOGGER.info('Deliveries:')
            for item in deliveries:
                grocer.LOGGER.info(item)
        else:
            grocer.LOGGER.info('No deliveries.')
        discounts = grocer.grocery.discounts
        if discounts:
            grocer.LOGGER.info('Discounts:')
            for item in discounts:
                grocer.LOGGER.info(item)
        else:
            grocer.LOGGER.info('No discounts.')


if __name__ == "__main__":
    main()
